### ISSUE TITLE
Samtools error

### ISSUE THREAD

**Issue by vaofford** [cancerit/pycroquet#17]
Version 1.5.1 (also tested with 1.3.0 with file which was previously working) on Sanger farm5.

```
INFO: Total unique guides: 7873
INFO: Number of duplicate guide-pairs: 680
INFO: Collating pairs from /lustre/scratch117/casm/team113/user/vo1/5429_vicky_dgcrispr_paralogs/29248_1#5.cram to /tmp/tmp0jwd19hf/collated.reads.bam
[E::easy_errno] Libcurl reported error 77 (Problem with the SSL CA cert (path? access rights?))
[W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/1b22b98cdeb4a9304cb5d48026a85128": Input/output error
[E::fai_build3_core] Failed to open the file /nfs/gs01/repository/references/Homo_sapiens/1000Genomes_hs37d5/all/fasta/hs37d5.fa
[E::refs_load_fai] Failed to open reference file '/nfs/gs01/repository/references/Homo_sapiens/1000Genomes_hs37d5/all/fasta/hs37d5.fa'
[E::cram_get_ref] Failed to populate reference for id 0
[E::cram_decode_slice] Unable to fetch reference #0:18050-1333998

[E::cram_next_slice] Slice decode failure
[E::easy_errno] Libcurl reported error 77 (Problem with the SSL CA cert (path? access rights?))
[W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/1b22b98cdeb4a9304cb5d48026a85128": Input/output error
[E::fai_build3_core] Failed to open the file /nfs/gs01/repository/references/Homo_sapiens/1000Genomes_hs37d5/all/fasta/hs37d5.fa
[E::refs_load_fai] Failed to open reference file '/nfs/gs01/repository/references/Homo_sapiens/1000Genomes_hs37d5/all/fasta/hs37d5.fa'
[E::cram_get_ref] Failed to populate reference for id 0
[E::cram_decode_slice] Unable to fetch reference #0:1333979-1334697

[E::easy_errno] Libcurl reported error 77 (Problem with the SSL CA cert (path? access rights?))
[W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/1b22b98cdeb4a9304cb5d48026a85128": Input/output error
[E::fai_build3_core] Failed to open the file /nfs/gs01/repository/references/Homo_sapiens/1000Genomes_hs37d5/all/fasta/hs37d5.fa
[E::refs_load_fai] Failed to open reference file '/nfs/gs01/repository/references/Homo_sapiens/1000Genomes_hs37d5/all/fasta/hs37d5.fa'
[E::cram_get_ref] Failed to populate reference for id 0
[E::cram_decode_slice] Unable to fetch reference #0:1334677-3102970

Traceback (most recent call last):
  File "/opt/wsi-t78/venv/bin/pycroquet", line 33, in <module>
    sys.exit(load_entry_point('pycroquet==1.5.1', 'console_scripts', 'pycroquet')())
  File "/opt/wsi-t78/venv/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/wsi-t78/venv/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/wsi-t78/venv/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/wsi-t78/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/wsi-t78/venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/wsi-t78/venv/lib/python3.9/site-packages/pycroquet-1.5.1-py3.9.egg/pycroquet/cli.py", line 217, in wrapper
  File "/opt/wsi-t78/venv/lib/python3.9/site-packages/pycroquet-1.5.1-py3.9.egg/pycroquet/cli.py", line 130, in wrapper
  File "/opt/wsi-t78/venv/lib/python3.9/site-packages/pycroquet-1.5.1-py3.9.egg/pycroquet/cli.py", line 237, in wrapper
  File "/opt/wsi-t78/venv/lib/python3.9/site-packages/pycroquet-1.5.1-py3.9.egg/pycroquet/cli.py", line 286, in dual_guide
  File "/opt/wsi-t78/venv/lib/python3.9/site-packages/pycroquet-1.5.1-py3.9.egg/pycroquet/dualguide.py", line 528, in run
  File "/opt/wsi-t78/venv/lib/python3.9/site-packages/pycroquet-1.5.1-py3.9.egg/pycroquet/readparser.py", line 323, in collate
  File "/opt/wsi-t78/venv/lib/python3.9/site-packages/pysam/utils.py", line 69, in __call__
    raise SamtoolsError(
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=Error reading input file\n'
```

**Comment by keiranmraine** [comment]
What you are seeing is a failure to use the EBI reference server, most likely due to expired certificates.

This can be resolved by setting the `REF_CACHE` and `REF_PATH` variables to an appropriate set of values:

http://www.htslib.org/doc/samtools.html#ENVIRONMENT_VARIABLES

You can also pre-populate REF_CACHE so it doesn't have to hit the server at all (but you should point it at a location other than `$HOME/.cache`).

**Comment by vaofford** [comment]
If running from a Singularity container this will need prefixing i.e. `SINGULARITYENV_REF_PATH` to be picked up by the container.
